### ISSUE TITLE
Issue with libevent on compiling

### ISSUE THREAD

**Issue by AlienKnuckle** [washingtondc-emu/washingtondc#17]
bash-4.4$ make
Scanning dependencies of target sh4
[  1%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4.c.o
[  2%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4_excp.c.o
[  4%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4_inst.c.o
[  5%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4_mem.c.o
[  7%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4_mmu.c.o
[  8%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4_reg.c.o
[ 10%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4_scif.c.o
[ 11%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4_tmu.c.o
[ 13%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4_ocache.c.o
[ 14%] Building C object CMakeFiles/sh4.dir/src/hw/g1/g1_reg.c.o
[ 16%] Building C object CMakeFiles/sh4.dir/src/hw/g2/g2_reg.c.o
[ 17%] Building C object CMakeFiles/sh4.dir/src/hw/gdrom/gdrom_reg.c.o
[ 19%] Building C object CMakeFiles/sh4.dir/src/hw/g2/modem.c.o
[ 20%] Building C object CMakeFiles/sh4.dir/src/hw/pvr2/pvr2_reg.c.o
[ 22%] Building C object CMakeFiles/sh4.dir/src/hw/pvr2/pvr2_core_reg.c.o
[ 23%] Building C object CMakeFiles/sh4.dir/src/hw/pvr2/pvr2_tex_mem.c.o
[ 25%] Building C object CMakeFiles/sh4.dir/src/hw/pvr2/spg.c.o
[ 26%] Building C object CMakeFiles/sh4.dir/src/hw/pvr2/pvr2_ta.c.o
[ 27%] Building C object CMakeFiles/sh4.dir/src/hw/pvr2/pvr2_tex_cache.c.o
[ 29%] Building C object CMakeFiles/sh4.dir/src/hw/pvr2/geo_buf.c.o
[ 30%] Building C object CMakeFiles/sh4.dir/src/hw/sys/sys_block.c.o
[ 32%] Building C object CMakeFiles/sh4.dir/src/hw/sys/holly_intc.c.o
[ 33%] Building C object CMakeFiles/sh4.dir/src/hw/maple/maple.c.o
[ 35%] Building C object CMakeFiles/sh4.dir/src/hw/maple/maple_device.c.o
[ 36%] Building C object CMakeFiles/sh4.dir/src/hw/maple/maple_controller.c.o
[ 38%] Building C object CMakeFiles/sh4.dir/src/hw/maple/maple_reg.c.o
[ 39%] Building C object CMakeFiles/sh4.dir/src/hw/aica/aica_reg.c.o
[ 41%] Building C object CMakeFiles/sh4.dir/src/hw/aica/aica_rtc.c.o
[ 42%] Building C object CMakeFiles/sh4.dir/src/hw/aica/aica_wave_mem.c.o
[ 44%] Building C object CMakeFiles/sh4.dir/src/BiosFile.c.o
[ 45%] Building C object CMakeFiles/sh4.dir/src/flash_memory.c.o
[ 47%] Building C object CMakeFiles/sh4.dir/src/memory.c.o
[ 48%] Building C object CMakeFiles/sh4.dir/src/MemoryMap.c.o
[ 50%] Building C object CMakeFiles/sh4.dir/src/dreamcast.c.o
[ 51%] Building C object CMakeFiles/sh4.dir/src/dc_sched.c.o
[ 52%] Building C object CMakeFiles/sh4.dir/src/win/glfw/window.c.o
[ 54%] Building C object CMakeFiles/sh4.dir/src/hw/pvr2/framebuffer.c.o
[ 55%] Building C object CMakeFiles/sh4.dir/src/gfx/opengl/shader.c.o
[ 57%] Building C object CMakeFiles/sh4.dir/src/gfx/opengl/opengl_output.c.o
[ 58%] Building C object CMakeFiles/sh4.dir/src/gfx/opengl/opengl_target.c.o
[ 60%] Building C object CMakeFiles/sh4.dir/src/gfx/opengl/opengl_renderer.c.o
[ 61%] Building C object CMakeFiles/sh4.dir/src/gfx/gfx_thread.c.o
[ 63%] Building C object CMakeFiles/sh4.dir/src/error.c.o
[ 64%] Building C object CMakeFiles/sh4.dir/src/stringlib.c.o
[ 66%] Building C object CMakeFiles/sh4.dir/src/gdi.c.o
[ 67%] Building C object CMakeFiles/sh4.dir/src/mount.c.o
[ 69%] Building C object CMakeFiles/sh4.dir/src/cdrom.c.o
[ 70%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4_dmac.c.o
[ 72%] Building C object CMakeFiles/sh4.dir/src/hw/sh4/sh4_tbl.c.o
[ 73%] Building C object CMakeFiles/sh4.dir/src/win/win_thread.c.o
[ 75%] Building C object CMakeFiles/sh4.dir/src/io/io_thread.c.o
/home/alienknuckle/Apps/Emulators/washingtondc/src/io/io_thread.c: In function ‘io_main’:
/home/alienknuckle/Apps/Emulators/washingtondc/src/io/io_thread.c:109:25: error: ‘EVLOOP_NO_EXIT_ON_EMPTY’ undeclared (first use in this function)
     int const evflags = EVLOOP_NO_EXIT_ON_EMPTY;
                         ^~~~~~~~~~~~~~~~~~~~~~~
/home/alienknuckle/Apps/Emulators/washingtondc/src/io/io_thread.c:109:25: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [CMakeFiles/sh4.dir/build.make:1263: CMakeFiles/sh4.dir/src/io/io_thread.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/sh4.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

**Comment by snickerbockers** [comment]
That's caused by not having the latest version of libevent installed.  A
lot of linux distro pacakge repos are a couple versions behind, but
WashingtonDC needs a feature that was introduced recently.  Installing
version 2.1.8-stable from the libevent website (libevent.org) will fix this.
