### ISSUE TITLE
Arm Dynarec supported?

### ISSUE THREAD

**Issue by Ntemis** [washingtondc-emu/washingtondc#29]
Hi, amazing work kudos.
Is in your plans to support arm dynarec?
Am very interested to implement your emu in Lakka as a libretro core

**Comment by snickerbockers** [comment]
ARM support is definitely something I'm going to do eventually, but it won't be for another 2-3 years at least because right now WashingtonDC isn't even running at fullspeed on x86.

There'll be a libretro core eventually too, but that's also a year or two into the future.

**Comment by Ntemis** [comment]
Amazing, will be checking at your excellent work until that time comes. Thanks
