### ISSUE TITLE
Aucune règle pour fabriquer la cible « lib/libevent.a »

### ISSUE THREAD

**Issue by MJB-G** [washingtondc-emu/washingtondc#36]
Hi

When I try to build washingtondc, I have this error : 

 Scanning dependencies of target washingtondc
[ 88%] Building C object CMakeFiles/washingtondc.dir/src/BiosFile.c.o
[ 89%] Building C object CMakeFiles/washingtondc.dir/src/main.c.o
make[2]: ***  Aucune règle pour fabriquer la cible « lib/libevent.a », nécessaire pour « washingtondc ». Arrêt.
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/washingtondc.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

Thank for your help.

**Comment by MJB-G** [comment]
Manjaro and cmake 3.10.2.

**Comment by snickerbockers** [comment]
I was able to reproduce your bug on a Manjaro VM, and I just pushed a few new commits to master that should fix it.  One of those commits added a new git submodule, so you'll have to run the following commands after you pull in the new commits:

```
git submodule init && git submodule update
```

Alternatively, you can make a new clone with the --recursive option to do this automatically.

Thanks for reporting this bug, and let me know if it works for you now or not.

**Comment by MJB-G** [comment]
It works, thank you!
