### ISSUE TITLE
file name with space

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [washingtondc-emu/washingtondc#39]
If gdi file contains files whose names are with space (such as "file with space.bin"), washingtondc fails to read such files.

**Comment by snickerbockers** [comment]
Thanks for reporting this.  I've pushed a commit that fixes the gdi code so that track filenames bound by quotes don't get split up by whitespace.  Let me know if this fixes it for you.

**Comment by tokumeiwokiboushimasu** [comment]
Thanks. I checked the problem has been fixed.
