### ISSUE TITLE
Key settings?

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [washingtondc-emu/washingtondc#48]
Could you add a functionality to specify a config file and write keyboard settings in it?
I always modify src/glfw/window.c when building washingtondc, but it is a bother.  Please.

**Comment by snickerbockers** [comment]
Sorry for the delayed response on this.

I've push out a set of commits which finally gives WashingtonDC its own config file.  It's located at "$XDG_CONFIG_HOME/washdc/wash.cfg", or "$HOME/.config/washdc/wash.cfg" if that's not defined.  WashingtonDC will automatically create this file if it doesn't exist, so it'll be there next time you run a new build.  After that, you can make changes to it to rebind the controls.

There's no documentation yet, so feel free to ask any questions you need to.  I'll also be adding more settings to this as time goes on, so let me know if there's anything else you want in it.

**Comment by tokumeiwokiboushimasu** [comment]
Thank you very much for adding this.
But there are the following building issues.

/home/hoge/washingtondc/src/glfw/control_bind.c: In function 'ctrl_get_gamepad_hat_state':
/home/hoge/washingtondc/src/glfw/control_bind.c:152:38: error: implicit declaration of function 'glfwGetJoystickHats'; did you mean 'glfwGetJoystickName'? [-Werror=implicit-function-declaration]
     const unsigned char *hat_state = glfwGetJoystickHats(btn->js, &len);
                                      ^~~~~~~~~~~~~~~~~~~
                                      glfwGetJoystickName
/home/hoge/washingtondc/src/glfw/control_bind.c:152:38: error: initialization of 'const unsigned char *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
/home/hoge/washingtondc/src/glfw/control_bind.c: In function 'ctrl_get_gamepad_hat_axis_state':
/home/hoge/washingtondc/src/glfw/control_bind.c:206:38: error: initialization of 'const unsigned char *' from 'int' makes pointer from integer without a cast [-Werror=int-conversion]
     const unsigned char *hat_state = glfwGetJoystickHats(btn->js, &len);
                                      ^~~~~~~~~~~~~~~~~~~
/home/hoge/washingtondc/src/glfw/control_bind.c: In function 'ctrl_parse_bind':
/home/hoge/washingtondc/src/glfw/control_bind.c:324:35: error: 'GLFW_HAT_UP' undeclared (first use in this function); did you mean 'GLFW_KEY_UP'?
             bind->ctrl.hat.mask = GLFW_HAT_UP;
                                   ^~~~~~~~~~~
                                   GLFW_KEY_UP
/home/hoge/washingtondc/src/glfw/control_bind.c:324:35: note: each undeclared identifier is reported only once for each function it appears in
/home/hoge/washingtondc/src/glfw/control_bind.c:326:35: error: 'GLFW_HAT_LEFT' undeclared (first use in this function); did you mean 'GLFW_KEY_LEFT'?
             bind->ctrl.hat.mask = GLFW_HAT_LEFT;
                                   ^~~~~~~~~~~~~
                                   GLFW_KEY_LEFT
/home/hoge/washingtondc/src/glfw/control_bind.c:328:35: error: 'GLFW_HAT_DOWN' undeclared (first use in this function); did you mean 'GLFW_KEY_DOWN'?
             bind->ctrl.hat.mask = GLFW_HAT_DOWN;
                                   ^~~~~~~~~~~~~
                                   GLFW_KEY_DOWN
/home/hoge/washingtondc/src/glfw/control_bind.c:330:35: error: 'GLFW_HAT_RIGHT' undeclared (first use in this function); did you mean 'GLFW_KEY_RIGHT'?
             bind->ctrl.hat.mask = GLFW_HAT_RIGHT;
                                   ^~~~~~~~~~~~~~
                                   GLFW_KEY_RIGHT
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/sh4.dir/build.make:557: CMakeFiles/sh4.dir/src/glfw/control_bind.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/sh4.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

**Comment by tokumeiwokiboushimasu** [comment]
Oops, I forgot    $ git submodlue update -i
It compiles.  Sorry.

**Comment by tokumeiwokiboushimasu** [comment]
And I could set up key bindings.  Thank you.
