### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [washingtondc-emu/washingtondc#51]
Hi, I'm using gcc-8.2.1 on Fedora28.  The following error occurs when building washingtonDC.

In file included from /home/hoge/washingtondc/src/io/washdbg_tcp.h:26,
                 from /home/hoge/washingtondc/src/dreamcast.c:75:
/home/hoge/washingtondc/src/dbg/debugger.h:27:2: error: #error This file should 
not be included unless the debugger is enabled
 #error This file should not be included unless the debugger is enabled
  ^~~~~
In file included from /home/hoge/washingtondc/src/dreamcast.c:75:
/home/hoge/washingtondc/src/io/washdbg_tcp.h:29:2: error: #error This file shoul
d not be included unless the debugger is enabled
 #error This file should not be included unless the debugger is enabled
  ^~~~~
/home/hoge/washingtondc/src/dreamcast.c: In function 'dreamcast_init':
/home/hoge/washingtondc/src/dreamcast.c:303:1: error: label 'on_init_complete' d
efined but not used [-Werror=unused-label]
 on_init_complete:
 ^~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/sh4.dir/build.make:531: CMakeFiles/sh4.dir/src/dreamcas
t.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/sh4.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

**Comment by snickerbockers** [comment]
Thanks for reporting this.  I just pushed out a new commit which should fix it.  Let me know if this fixes the build on your PC or not.

**Comment by tokumeiwokiboushimasu** [comment]
The build is fixed.  Thank you.
