### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [washingtondc-emu/washingtondc#55]
The following error occurs.

/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c: In function 'sh4_inst_unary_trapa_disp':
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:2014:17: error: unused variable 'sh4' [-Werror=unused-variable]
     struct Sh4 *sh4 = (struct Sh4*)cpu;
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c: In function 'sh4_inst_unary_fldi1_fr':
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:4670:17: error: 'sh4' undeclared (first use in this function); did you mean 'Sh4'?
     CHECK_FPSCR(sh4->reg[SH4_REG_FPSCR], SH4_FPSCR_PR_MASK, 0);
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:110:20: note: in definition of macro 'CHECK_FPSCR'
     do_check_fpscr(fpscr, mask, expect, __LINE__, __FILE__, __func__)
                    ^~~~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:4670:17: note: each undeclared identifier is reported only once for each function it appears in
     CHECK_FPSCR(sh4->reg[SH4_REG_FPSCR], SH4_FPSCR_PR_MASK, 0);
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:110:20: note: in definition of macro 'CHECK_FPSCR'
     do_check_fpscr(fpscr, mask, expect, __LINE__, __FILE__, __func__)
                    ^~~~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c: In function 'sh4_inst_binary_fmov_indgen_dr':
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:4836:17: error: 'sh4' undeclared (first use in this function); did you mean 'Sh4'?
     CHECK_FPSCR(sh4->reg[SH4_REG_FPSCR], SH4_FPSCR_SZ_MASK, SH4_FPSCR_SZ_MASK);
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:110:20: note: in definition of macro 'CHECK_FPSCR'
     do_check_fpscr(fpscr, mask, expect, __LINE__, __FILE__, __func__)
                    ^~~~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c: In function 'sh4_inst_binary_fmov_dr_xd':
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:5874:17: error: 'sh4' undeclared (first use in this function); did you mean 'Sh4'?
     CHECK_FPSCR(sh4->reg[SH4_REG_FPSCR], SH4_FPSCR_SZ_MASK, SH4_FPSCR_SZ_MASK);
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:110:20: note: in definition of macro 'CHECK_FPSCR'
     do_check_fpscr(fpscr, mask, expect, __LINE__, __FILE__, __func__)
                    ^~~~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c: In function 'sh4_inst_binary_fmov_xd_dr':
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:5892:17: error: 'sh4' undeclared (first use in this function); did you mean 'Sh4'?
     CHECK_FPSCR(sh4->reg[SH4_REG_FPSCR], SH4_FPSCR_SZ_MASK, SH4_FPSCR_SZ_MASK);
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:110:20: note: in definition of macro 'CHECK_FPSCR'
     do_check_fpscr(fpscr, mask, expect, __LINE__, __FILE__, __func__)
                    ^~~~~
cc1: all warnings being treated as errors
make[2]: *** [CMakeFiles/sh4.dir/build.make:89: CMakeFiles/sh4.dir/src/hw/sh4/sh4_inst.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/sh4.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

**Comment by snickerbockers** [comment]
Thanks for reporting this.  I just pushed out a commit which should fix it.  Let me know if it works on your machine now or not.

**Comment by tokumeiwokiboushimasu** [comment]
Sorry for my late reply.  There are still the following errors.

/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c: In function 'sh4_inst_unary_fldi1_fr':
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:4670:17: error: 'sh4' undeclared (first use in this function); did you mean 'Sh4'?
     CHECK_FPSCR(sh4->reg[SH4_REG_FPSCR], SH4_FPSCR_PR_MASK, 0);
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:110:20: note: in definition of macro 'CHECK_FPSCR'
     do_check_fpscr(fpscr, mask, expect, __LINE__, __FILE__, __func__)
                    ^~~~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:4670:17: note: each undeclared identifier is reported only once for each function it appears in
     CHECK_FPSCR(sh4->reg[SH4_REG_FPSCR], SH4_FPSCR_PR_MASK, 0);
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:110:20: note: in definition of macro 'CHECK_FPSCR'
     do_check_fpscr(fpscr, mask, expect, __LINE__, __FILE__, __func__)
                    ^~~~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c: In function 'sh4_inst_binary_fmov_indgen_dr':
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:4836:17: error: 'sh4' undeclared (first use in this function); did you mean 'Sh4'?
     CHECK_FPSCR(sh4->reg[SH4_REG_FPSCR], SH4_FPSCR_SZ_MASK, SH4_FPSCR_SZ_MASK);
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:110:20: note: in definition of macro 'CHECK_FPSCR'
     do_check_fpscr(fpscr, mask, expect, __LINE__, __FILE__, __func__)
                    ^~~~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c: In function 'sh4_inst_binary_fmov_dr_xd':
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:5874:17: error: 'sh4' undeclared (first use in this function); did you mean 'Sh4'?
     CHECK_FPSCR(sh4->reg[SH4_REG_FPSCR], SH4_FPSCR_SZ_MASK, SH4_FPSCR_SZ_MASK);
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:110:20: note: in definition of macro 'CHECK_FPSCR'
     do_check_fpscr(fpscr, mask, expect, __LINE__, __FILE__, __func__)
                    ^~~~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c: In function 'sh4_inst_binary_fmov_xd_dr':
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:5892:17: error: 'sh4' undeclared (first use in this function); did you mean 'Sh4'?
     CHECK_FPSCR(sh4->reg[SH4_REG_FPSCR], SH4_FPSCR_SZ_MASK, SH4_FPSCR_SZ_MASK);
                 ^~~
/home/hoge/washingtondc/src/hw/sh4/sh4_inst.c:110:20: note: in definition of macro 'CHECK_FPSCR'
     do_check_fpscr(fpscr, mask, expect, __LINE__, __FILE__, __func__)
                    ^~~~~
make[2]: *** [CMakeFiles/sh4.dir/build.make:89: CMakeFiles/sh4.dir/src/hw/sh4/sh4_inst.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/sh4.dir/all] Error 2
make: *** [Makefile:95: all] Error 2

**Comment by snickerbockers** [comment]
Okay, it looks like my first commit missed a spot.  I pushed out a new one which should hopefully fix it for good, let me know if it works or not.

**Comment by tokumeiwokiboushimasu** [comment]
Fixed.  Thank you.
