### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by tokumeiwokiboushimasu** [washingtondc-emu/washingtondc#58]
Cmake fails on Fedora.  The error message is bellow.

CMake Error at src/washingtondc/CMakeLists.txt:123 (add_executable):
  Cannot find source file:

    /home/hoge/washingtondc/src/washingtondc/washingtondc.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at src/washingtondc/CMakeLists.txt:123 (add_executable):
  No SOURCES given to target: washingtondc

**Comment by snickerbockers** [comment]
Thanks for catching this!  It looks like in my latest commit I forgot to add that file to git.  I've just pushed out a new commit which adds it.

**Comment by tokumeiwokiboushimasu** [comment]
Fixed.  Thanks.

**Comment by MJBG** [comment]
I have the same problem.

**Comment by snickerbockers** [comment]
@MJBG what's the exact error message you're seeing?

**Comment by MJBG** [comment]
CMake Error at src/washingtondc/CMakeLists.txt:123 (add_executable):
  Cannot find source file:

    /washingtondc-master/external/sh4asm/sh4asm_core/disas.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at src/washingtondc/CMakeLists.txt:123 (add_executable):
  No SOURCES given to target: washingtondc

**Comment by snickerbockers** [comment]
that means that it's missing the git submodules.  You can fix this by running `git submodule init && git submodule update`.  Alternatively, you can checkout a new copy of the source with the `--recursive` flag and that will do it automatically.

**Comment by MJBG** [comment]
thanks !
